const fighters = {
  charles: {
    fname: "Charles",
    lname: "Oliveira",
    wins: 33,
    losses: 8,
    draws: 0,
    noContests: 0,
    weight: "155",
    height: "68",
  },
  islam: {
    fname: "Islam",
    lname: "Makhachev",
    wins: 22,
    losses: 1,
    draws: 0,
    noContests: 0,
    weight: "155",
    height: "68",
  },
  aljo: {
    fname: "Aljamain",
    lname: "Sterling",
    wins: 21,
    losses: 3,
    draws: 0,
    noContests: 0,
    weight: "135",
    height: "67",
  },
  tj: {
    fname: "T.J.",
    lname: "Dillashaw",
    wins: 18,
    losses: 4,
    draws: 0,
    noContests: 0,
    weight: "135",
    height: "67",
  },
  suga: {
    fname: "Sean",
    lname: "O'Malley",
    wins: 15,
    losses: 1,
    draws: 0,
    noContests: 1,
    weight: "135",
    height: "67",
  },
  petr: {
    fname: "Petr",
    lname: "Yan",
    wins: 16,
    losses: 3,
    draws: 0,
    noContests: 0,
    weight: "135",
    height: "67",
  },
  izzy: {
    fname: "Israel",
    lname: "Adesanya",
    wins: 23,
    losses: 1,
    draws: 0,
    noContests: 0,
    weight: "185",
    height: "76",
  },
  pereira: {
    fname: "Alex",
    lname: "Pereira",
    wins: 6,
    losses: 1,
    draws: 0,
    noContests: 0,
    weight: "185",
    height: "76",
  },
  dustin: {
    fname: "Dustin",
    lname: "Poirier",
    wins: 28,
    losses: 7,
    draws: 0,
    noContests: 1,
    weight: "155",
    height: "68",
  },
  chandler: {
    fname: "Michael",
    lname: "Chandler",
    wins: 23,
    losses: 7,
    draws: 0,
    noContests: 0,
    weight: "155",
    height: "67",
  },
  esparza: {
    fname: "Carla",
    lname: "Esparza",
    wins: 20,
    losses: 6,
    draws: 0,
    noContests: 0,
    weight: "115",
    height: "63",
  },
  zhang: {
    fname: "Weili",
    lname: "Zhang",
    wins: 22,
    losses: 3,
    draws: 0,
    noContests: 0,
    weight: "115",
    height: "63",
  },
};

export default fighters;
